[package]
name = "vimcal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
dasp = "0.11.0"
enigo = "0.2.1"
state = "0.6.0"
vosk = "0.2.0"
